/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canteenmanagement;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        resizeLogoTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWrapperOuter = new javax.swing.JPanel();
        panelWrapperInner = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        labelLogoIcon = new javax.swing.JLabel();
        labelTitle1 = new javax.swing.JLabel();
        labelTitle2 = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        signup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(995, 599));
        setMinimumSize(new java.awt.Dimension(995, 599));
        setResizable(false);

        panelWrapperOuter.setBackground(new java.awt.Color(215, 185, 155));

        panelWrapperInner.setBackground(new java.awt.Color(255, 255, 255));
        panelWrapperInner.setMaximumSize(new java.awt.Dimension(962, 569));
        panelWrapperInner.setMinimumSize(new java.awt.Dimension(962, 569));

        panelLeft.setBackground(new java.awt.Color(28, 42, 57));

        labelLogoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoCMS.png"))); // NOI18N

        labelTitle1.setFont(new java.awt.Font("Century Gothic", 1, 34)); // NOI18N
        labelTitle1.setForeground(new java.awt.Color(255, 179, 71));
        labelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle1.setText("Canteen Management");

        labelTitle2.setFont(new java.awt.Font("Century Gothic", 1, 34)); // NOI18N
        labelTitle2.setForeground(new java.awt.Color(255, 179, 71));
        labelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle2.setText("System");

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(labelLogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(labelTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(labelLogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitle2)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        panelRight.setBackground(new java.awt.Color(255, 255, 255));
        panelRight.setMaximumSize(new java.awt.Dimension(506, 624));
        panelRight.setMinimumSize(new java.awt.Dimension(506, 624));

        loginLabel.setFont(new java.awt.Font("Century Gothic", 1, 34)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");

        username.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 13))); // NOI18N

        login.setBackground(new java.awt.Color(28, 42, 57));
        login.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        login.setSelected(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        labelStatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(0, 255, 0));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        text.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        text.setText("No account? Create one.");

        signup.setBackground(new java.awt.Color(0, 0, 0));
        signup.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        signup.setForeground(new java.awt.Color(0, 104, 104));
        signup.setText("Sign Up");
        signup.setContentAreaFilled(false);
        signup.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        signup.setFocusable(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRightLayout = new javax.swing.GroupLayout(panelRight);
        panelRight.setLayout(panelRightLayout);
        panelRightLayout.setHorizontalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelRightLayout.createSequentialGroup()
                            .addComponent(text)
                            .addGap(10, 10, 10)
                            .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRightLayout.setVerticalGroup(
            panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRightLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(loginLabel)
                .addGap(51, 51, 51)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(panelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRightLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(text))
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelWrapperInnerLayout = new javax.swing.GroupLayout(panelWrapperInner);
        panelWrapperInner.setLayout(panelWrapperInnerLayout);
        panelWrapperInnerLayout.setHorizontalGroup(
            panelWrapperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrapperInnerLayout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelWrapperInnerLayout.setVerticalGroup(
            panelWrapperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrapperInnerLayout.createSequentialGroup()
                .addGroup(panelWrapperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelWrapperOuterLayout = new javax.swing.GroupLayout(panelWrapperOuter);
        panelWrapperOuter.setLayout(panelWrapperOuterLayout);
        panelWrapperOuterLayout.setHorizontalGroup(
            panelWrapperOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrapperOuterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelWrapperInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelWrapperOuterLayout.setVerticalGroup(
            panelWrapperOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWrapperOuterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelWrapperInner, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapperOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWrapperOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void userLogin() {
        String user = username.getText();
        String pw = String.valueOf(password.getPassword());
        
        Database db = new Database();
        
        User userLoggedIn = db.userLogin(user, pw);
        
        if (userLoggedIn != null) {
            Dashboard dashboard = new Dashboard(userLoggedIn);
            dashboard.setVisible(true);
            dashboard.pack();
            dashboard.setLocationRelativeTo(null);
            this.dispose();
        }
    }
    
    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFocusGained

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        userLogin();
    }//GEN-LAST:event_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        SignUp signupFrame = new SignUp();
        signupFrame.setVisible(true);
        signupFrame.pack();
        signupFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_signupActionPerformed
    
    public void resizeLogoTitle() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/logoCMS.png"));

        int width = labelLogoIcon.getWidth();
        int height = labelLogoIcon.getHeight();

        Image img = icon.getImage();
        int imgWidth = icon.getIconWidth();
        int imgHeight = icon.getIconHeight();

        float widthRatio = (float) width / imgWidth;
        float heightRatio = (float) height / imgHeight;
        float scale = Math.min(widthRatio, heightRatio);

        int newWidth = (int) (imgWidth * scale);
        int newHeight = (int) (imgHeight * scale);

        Image scaledImg = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
        labelLogoIcon.setIcon(new ImageIcon(scaledImg));
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelLogoIcon;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTitle1;
    private javax.swing.JLabel labelTitle2;
    private javax.swing.JButton login;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelWrapperInner;
    private javax.swing.JPanel panelWrapperOuter;
    private javax.swing.JPasswordField password;
    public javax.swing.JButton signup;
    private javax.swing.JLabel text;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
